#!/usr/bin/env bash

# Add <%aE> to the format string to get emails too
AUTHORS=$(git log --format='%aN' | sort -u |
    while read LINE
    do
        printf "* $LINE\n"
    done
)
DATE=$(date +%Y-%m-%d)
COMMIT=$(git log -n 1 --format='%h')

cat << EOF
The following people have contributed to Simple Bandwidth Scanner.
Thank you for helping make Tor better.

$AUTHORS

*Last updated: $DATE on $COMMIT*
EOF
